/**
 * http请求异常码
 */
export enum ExceptionEnum {
  BAD_REQUEST = 400,
  PAGE_NOT_ACCESS = 403,
  PAGE_NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  INTERNAL_SERVER_ERROR = 500,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}